"""
Build a single human-readable catalog of every Spider database: tables, columns,
types and foreign keys, plus the clusters of databases that are hard to tell
apart from a question alone.

Motivation: with app.py's auto-detect on, picking the wrong database guarantees
a wrong answer, and the flight_1 / flight_2 / flight_4 / flight_company family
showed that "which database is this question about?" is genuinely ambiguous for
whole clusters of Spider schemas. A flat list of column names does not surface
that; the confusable-cluster section does, using the same BM25 document
representation src/db_selector.py ranks with, so the clusters it reports are the
ones the selector actually confuses rather than ones that merely look similar.

    python -m scripts.build_schema_catalog                  # -> docs/schema_catalog.md
    python -m scripts.build_schema_catalog --track nosql    # -> docs/schema_catalog_nosql.md
"""

from __future__ import annotations

import argparse
import glob
import json
import os

from src.db_selector import DBSelector, _db_document

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def _load(track: str) -> dict[str, dict]:
    out = {}
    for path in sorted(glob.glob(os.path.join(
            HERE, "Data", "prompt_schema", track, "*.json"))):
        db = os.path.splitext(os.path.basename(path))[0]
        with open(path, encoding="utf-8") as f:
            out[db] = json.load(f)
    return out


def _fk_graph(db: str) -> dict:
    path = os.path.join(HERE, "Data", "fk_graphs", f"{db}.json")
    if not os.path.exists(path):
        return {}
    with open(path, encoding="utf-8") as f:
        return json.load(f)


def _fks(graph: dict) -> list[str]:
    # The graph serializes relationships under "edges" (not networkx's "links").
    return [f"{e['from']}.{e['child_col']} -> {e['to']}.{e['parent_col']}"
            for e in graph.get("edges", [])]


def _primary_keys(graph: dict) -> dict[str, set[str]]:
    return {n["name"]: set(n.get("pk", [])) for n in graph.get("nodes", [])}


def _tables(schema: dict, pks: dict[str, set[str]]) -> dict[str, list[str]]:
    """table -> ["col:type", "col:type (PK)", ...] in PromptSchema order."""
    tables: dict[str, list[str]] = {}
    for key, meta in schema.items():
        table, _, column = key.partition(".")
        rendered = f"{column}:{(meta or {}).get('inferred_type', '?')}"
        if column in pks.get(table, ()):
            rendered += " (PK)"
        tables.setdefault(table, []).append(rendered)
    return tables


def _confusable(schemas: dict[str, dict], track: str, threshold: float) -> list[tuple]:
    """Databases whose own schema text retrieves another database strongly.

    Each database's BM25 document is used as a query against the index. If some
    other database scores close to the self-match, the two share so much schema
    vocabulary that a question mentioning only that shared vocabulary cannot be
    routed between them.
    """
    sel = DBSelector(track=track)
    rows = []
    for db, schema in schemas.items():
        ranked = sel.rank(_db_document(db, schema), k=4)
        if not ranked:
            continue
        self_score = next((s for n, s in ranked if n == db), None)
        if not self_score:
            continue
        rivals = [(n, s / self_score) for n, s in ranked
                  if n != db and s / self_score >= threshold]
        if rivals:
            rows.append((db, rivals))
    return sorted(rows, key=lambda r: -max(s for _, s in r[1]))


def build(track: str, threshold: float) -> str:
    schemas = _load(track)
    graphs = {db: _fk_graph(db) for db in schemas}
    n_tables = sum(len(_tables(s, _primary_keys(graphs[db])))
                   for db, s in schemas.items())
    n_cols = sum(len(s) for s in schemas.values())

    out = [
        f"# Spider schema catalog — {track.upper()} track",
        "",
        "Generated by `scripts/build_schema_catalog.py`; do not edit by hand.",
        "Source: `Data/prompt_schema/` (Phase 6) + `Data/fk_graphs/` (Phase 5A).",
        "",
        f"**{len(schemas)} databases, {n_tables} tables, {n_cols} columns.**",
        "",
        "## Confusable databases",
        "",
        "Pairs sharing enough schema vocabulary that a question mentioning only",
        "the shared terms cannot be routed between them. Scored with the same BM25",
        "representation `src/db_selector.py` uses, as a fraction of each database's",
        f"self-match (threshold {threshold:.0%}). These are where auto-detect fails,",
        "and where the demo's override matters most.",
        "",
        "| Database | Confusable with (similarity to self-match) |",
        "|---|---|",
    ]
    for db, rivals in _confusable(schemas, track, threshold):
        pretty = ", ".join(f"`{n}` ({s:.0%})" for n, s in rivals)
        out.append(f"| `{db}` | {pretty} |")

    out += ["", "## Databases", ""]
    for db, schema in schemas.items():
        graph = graphs[db]
        out.append(f"### `{db}`")
        out.append("")
        for table, cols in _tables(schema, _primary_keys(graph)).items():
            out.append(f"- **{table}** — {', '.join(cols)}")
        fks = _fks(graph)
        if fks:
            out.append("")
            out.append("  Foreign keys: " + "; ".join(f"`{f}`" for f in fks))
        out.append("")
    return "\n".join(out)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--track", default="sql", choices=["sql", "nosql"])
    ap.add_argument("--threshold", type=float, default=0.55,
                    help="Report rivals scoring at least this fraction of the self-match.")
    ap.add_argument("--out", default=None)
    args = ap.parse_args()

    suffix = "" if args.track == "sql" else f"_{args.track}"
    out = args.out or os.path.join(HERE, "docs", f"schema_catalog{suffix}.md")
    text = build(args.track, args.threshold)
    with open(out, "w", encoding="utf-8") as f:
        f.write(text)
    print(f"Wrote {out}  ({len(text) / 1024:.0f} KB)")


if __name__ == "__main__":
    main()
